import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to landing page, this page is not protected, to continute, login below!!!</h1>
        <p>When logged in, auth pages are not blocked from opening</p>

        <div>
          <Link
            href="/dashboard"
            className={styles.card}
          >
            <h2 className={inter.className}>
              dashboard <span>-&gt;</span>
            </h2>
          </Link>
          <Link
            href="/login"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Login <span>-&gt;</span>
            </h2>
          </Link>
          <Link
            href="/login"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Register <span>-&gt;</span>
            </h2>
          </Link>
        </div>
      </main>
    </>
  )
}
